services:
  python_server:
    build: .
    container_name: cashya-shoppy
    restart: unless-stopped
    volumes:
      - .:/myproject
      - data:/myproject/data
    ports:
      - 5025:5025

volumes:
  data:
    name: "cashya-shoppy-data"
