version: "3.8"

services:
  python_server:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - 8000:8000


