# Generated by Django 5.2.5 on 2025-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_category_options_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_sort_order', '-available', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category_product_sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
