# Generated by Django 5.2.5 on 2025-08-09 10:45

from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    Product = apps.get_model('ecom', 'Product')
    for product in Product.objects.all():
        product.slug = str(product.id)
        product.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    Product = apps.get_model('ecom', 'Product')
    Product.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
