services:
  backend:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    container_name: cashya-shoppy-backend-prod
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
      - ../../data:/app/data
    ports:
      - 8000:8000

volumes:
  data:
    name: "cashya-shoppy-data"
