# Generated by Django 4.2.16 on 2024-11-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Cashya Shoppy', max_length=255)),
                ('pg_charge', models.FloatField(default=2.0)),
                ('collect_from_customer', models.BooleanField(default=False)),
            ],
        ),
    ]
