# Generated by Django 5.0.7 on 2025-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_cod',
            field=models.BooleanField(default=True, help_text='Allow customers to pay via Cash on Delivery', verbose_name='Enable Cash on Delivery'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_paytm',
            field=models.BooleanField(default=False, help_text='Allow customers to pay using Paytm (requires PAYTM_MID and PAYTM_MERCHANT_KEY)', verbose_name='Enable Paytm Gateway'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_phonepe',
            field=models.BooleanField(default=False, help_text='Allow customers to pay using PhonePe (requires PHONEPE_MERCHANT_ID and PHONEPE_SALT_KEY)', verbose_name='Enable PhonePe Gateway'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_razorpay',
            field=models.BooleanField(default=False, help_text='Allow customers to pay using Razorpay (requires RAZORPAY_API_KEY and RAZORPAY_API_SECRET)', verbose_name='Enable Razorpay Gateway'),
        ),
    ]
