# Generated by Django 5.0.7 on 2025-09-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_cod',
            field=models.BooleanField(default=True, help_text='Allow customers to pay via Cash on Delivery', verbose_name='Enable Cash on Delivery'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_paytm',
            field=models.BooleanField(default=True, help_text='Allow customers to pay using Paytm', verbose_name='Enable Paytm Gateway'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_phonepe',
            field=models.BooleanField(default=True, help_text='Allow customers to pay using PhonePe', verbose_name='Enable PhonePe Gateway'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_razorpay',
            field=models.BooleanField(default=True, help_text='Allow customers to pay using Razorpay', verbose_name='Enable Razorpay Gateway'),
        ),
    ]
